\c treatments_db;

INSERT INTO treatments (name, treatment_image, category, description, price, therapist, therapist_image) 
VALUES
('The Classic Facial', 'https://www.wederm.com/wp-content/uploads/2021/06/What_Is_A_Facial-300x200.jpg', 'Facials', 'You never go wrong with a classic facial. Known as a one-shot deal that tackles most of your skin care needs, this facial treatment combines cleansing, exfoliation, extractions, and hydration into one service to help you beautify your complexion.', 100, 'Gunther', 'https://images.genius.com/71bf8921811f54ac42db1c16b8a18a66.400x400x1.jpg'),
('The Gentleman Facial', 'https://blog.californiaskincaresupply.com/wp-content/uploads/2022/04/man-beard-get-facial-1024x684.jpg', 'Facials', 'This effective treatment is designed to cleanse and soothe aggressive exposure related to sports and shaving. Pure plant-based products fortified with vitamins and antioxidants ensures visible results fit for a gentleman.', 85, 'Gunther', 'https://images.genius.com/71bf8921811f54ac42db1c16b8a18a66.400x400x1.jpg'),
('The Stem-Cell Facial', 'https://www.naturallookmedicalspa.com/wp-content/uploads/2019/07/Stem-Cell_header.jpg', 'Facials', 'A rejuvenating facial with the latest and most potent stem cells to help stimulate collagen and elastin, reduce inflammation, brighten the skin and dramatically reduce the appearance of fine lines and wrinkles leaving your skin luminous and restored.', 150, 'Kylie Jenner',  'https://wwd.com/wp-content/uploads/2021/07/1-KJC_MULTI_21_Main_KV1_Kylie_Digital_Square_HR.jpg'),
('The Deep Tissue Or I Will Break You Massage', 'https://pbs.twimg.com/media/CS6ff8zWwAAgr6k.jpg', 'Massages', 'A deeply therapeutic technique designed to pull stress out of tired muscles with strong and vigorous pressure. Targets sore spots, knots and muscle tension from sports, exercise, repetitive stress and overexertion, with deeply penetrating botanical extracts that ease muscle pain and soreness.', 155, 'Ivan Drago', 'https://i.imgflip.com/2lkegn.jpg'),
('The Rousey Reflexology Special', 'https://cdn.vox-cdn.com/thumbor/4gNMMad2SJxjL8iH1-VqIhany1I=/0x0:1191x766/1200x800/filters:focal(521x274:711x464)/cdn.vox-cdn.com/uploads/chorus_image/image/71554166/rouseykendosticks.0.jpg', 'Massages', 'One of the most deeply relaxing treatments available, Reflexology is based on a system of mapping the organs of the entire body through corresponding points on your feet. Our Highly trained therapist can help heal imbalances by massaging and stimulating specific points on the feet that will invigorate the entire body.', 175, 'Ronda Rousey', 'https://dmxg5wxfqgb4u.cloudfront.net/image/fighter_images/Ronda_Rousey/ROUSEY_RONDA.png?VersionId=ultyCf6g9SyT8zsHrIjOqMhjtYye7QKu'),
('The Swedish Finisher', 'https://i.pinimg.com/736x/5a/76/6e/5a766eb5713a9c7ab30653a184d07e8b.jpg', 'Massages', 'A Swedish soothing, full-body massage designed to revitalize sore muscles and calm the cluttered mind. Long & fluid strokes warm the body, enhance circulation and stimulate lymphatic flow, while targeted techniques smooth the connective tissue(fascia) that surrounds the muscles to release ultimate chronic tension and result in a deep sense of wellbeing.', 175, 'Ronda Rousey', 'https://dmxg5wxfqgb4u.cloudfront.net/image/fighter_images/Ronda_Rousey/ROUSEY_RONDA.png?VersionId=ultyCf6g9SyT8zsHrIjOqMhjtYye7QKu'),
('French Wax: The Landing Strip', 'https://static-bebeautiful-in.unileverservices.com/1200/900/bikini-french-and-brazilian-wax_MobileHome.jpg', 'Waxes', 'If you want to be smooth and clean of hair without feeling too bare, the French wax is perfect! With most of the hair removed from around the front and sides, the middle and around the back remains. The landing strip shape is a classic.', 30, 'Kylie Jenner', 'https://wwd.com/wp-content/uploads/2021/07/1-KJC_MULTI_21_Main_KV1_Kylie_Digital_Square_HR.jpg'),
('The Brazillian Bikini Wax', 'https://post.healthline.com/wp-content/uploads/2021/06/hip-and-thighs-of-an-unrecognizable-woman-wearing-a-swimsuit-732x549-thumbnail.jpg', 'Waxes', 'The Brazilian Bikini wax removes everything from front to back. 
a little bit is left in the front if requested. Also, you can request what is known as the Bermuda Triangle. It resembles a traditional bikini line wax with just a neat triangle of hair left.', 45, 'Kylie Jenner', 'https://wwd.com/wp-content/uploads/2021/07/1-KJC_MULTI_21_Main_KV1_Kylie_Digital_Square_HR.jpg'),
('The Hollywood', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Hollywood_Sign_%28Zuschnitt%29.jpg/1200px-Hollywood_Sign_%28Zuschnitt%29.jpg', 'Waxes', 'A Brazilian wax can sometimes leave a bit of hair. However, with a Hollywood wax, there is no hair left behind. Absolutely none. Be prepared to take your knickers off and do not feel embarrassed to get into some yoga-esque poses so your waxer can get everywhere', 50, 'Ivan Drago', 'https://i.imgflip.com/2lkegn.jpg'),
('The Hammam Experience', 'https://cdn.spafinder.com/2016/10/hammam-six-senses-kuwait-1024x640.jpeg', 'Body Treatments', 'Named after the traditional Middle Eastern bathing ceremony, Hammam, this luxurious exfoliating and moisturizing full body experience eliminates all traces of dry, flaky skin. Starts with a steam room session to prepare your skin for the deliciously scented, authentic, Moroccan black soap. After exfoliation from head to toe with a gentle glove that removes dead skin cells, You will follow up with being covered in Rhassoul clay that is sourced from the only known deposit in the world, located in the Middle Atlas Mountains which purifies and firms the skin. After the purification experience, the body is massaged with a dry argan Oil, leaving skin with a satin dry finish!', 200, 'Gunther', 'https://images.genius.com/71bf8921811f54ac42db1c16b8a18a66.400x400x1.jpg'),
('The Surf Turf Surprise', 'http://www.piedmont.org/media/BlogImages/mud-bath.jpg', 'Body Treatments', 'The piece de resistance of body therapies. We begin with a thorough all-over body scrub with super fine salts saturated in aromatic oil. You will then be cocooned in a hydrating and toning mud to replenish essential nutrients and nourish your newly "unearthed" skin. Lastly, a rich moisturizing cream is applied to the entire body for the perfect finish.', 180, 'Ronda Rousey', 'https://dmxg5wxfqgb4u.cloudfront.net/image/fighter_images/Ronda_Rousey/ROUSEY_RONDA.png?VersionId=ultyCf6g9SyT8zsHrIjOqMhjtYye7QKu'),
('The Hourglass', 'https://introvertplayground.files.wordpress.com/2016/06/human-pretzel.jpg?w=682', 'Body Treatments', 'This slimming, firming, toning, and detoxifying wrap combines plant extracts, caffeine, essential oils, and algae extract, and then uses both hot and cold thermal agents to stimulate fat burning. This improves the appearance of cellulite, varicose veins and stretch marks, and dramatically reduces "orange peel" skin. Most people lose 1-4 centimeters around their waists and thighs after the first treatment.', 175, 'Ivan Drago', 'https://i.imgflip.com/2lkegn.jpg');